### importing libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### importing and manipulating train data

In [6]:
train_data = pd.read_csv('data/train.csv')
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [25]:
sex = train_data.iloc[:,4:5].values.reshape(-1)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
sex = le.fit_transform(sex)
sex = pd.DataFrame(sex)
sex

0
0    1
1    0
2    0
3    0
4    1
..  ..
886  1
887  0
888  0
889  1
890  1

[891 rows x 1 columns]

In [9]:
age = train_data.iloc[:,5:6]
age

Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

In [10]:
age.isna().sum()

Age    177
dtype: int64

In [28]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(age)
age = imputer.transform(age)
age = pd.DataFrame(age)
age

0
0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
..         ...
886  27.000000
887  19.000000
888  29.699118
889  26.000000
890  32.000000

[891 rows x 1 columns]

In [27]:
age.isna().sum()

0    0
dtype: int64

In [12]:
p_class = train_data.iloc[:,2:3]

In [13]:
s1 = pd.concat([p_class, age], axis=1)
x_train = pd.concat([s1, sex], axis=1).values
x_train

array([[ 3.        , 22.        ,  1.        ],
       [ 1.        , 38.        ,  0.        ],
       [ 3.        , 26.        ,  0.        ],
       ...,
       [ 3.        , 29.69911765,  0.        ],
       [ 1.        , 26.        ,  1.        ],
       [ 3.        , 32.        ,  1.        ]])

In [34]:
y_train = train_data.iloc[:,1:2].values.reshape(-1)

### importing and manipulating test data

In [14]:
test_data = pd.read_csv('data/test.csv')
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [15]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [23]:
sex_test = test_data.iloc[:,3:4].values.reshape(-1)
from sklearn.preprocessing import LabelEncoder
le2 = LabelEncoder()
sex_test = le.fit_transform(sex_test)
sex_test = pd.DataFrame(sex_test)
sex_test

0
0    1
1    0
2    1
3    1
4    0
..  ..
413  1
414  0
415  1
416  1
417  1

[418 rows x 1 columns]

In [27]:
age_test = test_data.iloc[:,4:5].values
from sklearn.impute import SimpleImputer
imputer2 = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer2 = imputer2.fit(age_test)
age_test = imputer2.transform(age_test)
age_test = pd.DataFrame(age_test)
age.isna().sum()
age

0
0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
..         ...
886  27.000000
887  19.000000
888  29.699118
889  26.000000
890  32.000000

[891 rows x 1 columns]

In [29]:
p_class_test = test_data.iloc[:,1:2]

In [30]:
s2 = pd.concat([p_class_test, age_test], axis=1)
x_test = pd.concat([s2, sex_test], axis=1).values
x_test

array([[ 3.        , 34.5       ,  1.        ],
       [ 3.        , 47.        ,  0.        ],
       [ 2.        , 62.        ,  1.        ],
       ...,
       [ 3.        , 38.5       ,  1.        ],
       [ 3.        , 30.27259036,  1.        ],
       [ 3.        , 30.27259036,  1.        ]])

### scaling datas

In [36]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

### logistic regression model

In [37]:
from sklearn.linear_model import LogisticRegression

logr = LogisticRegression()
logr.fit(x_train_scaled, y_train)
y_pred_logr = logr.predict(x_test_scaled)
y_pred_logr

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [38]:
predicted = pd.DataFrame(y_pred_logr)
predicted

0
0    0
1    0
2    0
3    0
4    1
..  ..
413  0
414  1
415  0
416  0
417  0

[418 rows x 1 columns]

In [39]:
pass_id = test_data.iloc[:,0]
pass_id

0       892
1       893
2       894
3       895
4       896
       ... 
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64

In [40]:
final = pd.concat([pass_id, predicted], axis=1)
final.columns = ['PassengerId', 'Survived']
final

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [94]:
final.to_csv('submission.csv', index=False)

The accuracy value of this analysis was found to be 0.75837 by kaggle.